# Generated by Django 5.0.3 on 2024-03-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.service'),
            preserve_default=False,
        ),
    ]
